### ISSUE TITLE
Broken link on Zenodo?

### ISSUE THREAD

**Issue by TristanHehnen** [antonvs88/optimal-guided-evacuation#1]
Hi!

It apperas that the link on the [Zenodo repo page](https://zenodo.org/record/3824028#.XrvURcBCSUk), marked by the red circle, is broken or leading to a non-public GitHub repo.

![Screenshot_26](https://user-images.githubusercontent.com/34650649/81804864-28895a80-951a-11ea-9963-79d96a9aee48.png)

Could you please have a look at it?

Cheers,
Tristan

**Comment by antonvs88** [comment]
Hi Tristan!

Thanks for noticing it! I have now corrected the link.

edit. And thanks for accepting my repository to the Fire Safety Engineering and Evacuation community in Zenodo.

-Anton

**Comment by TristanHehnen** [comment]
You're welcome!
